services:
  - type: web
    name: eesa-website
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: SMTP_FROM_NAME
        value: "EESA SGGS"
      - key: COLLEGE_DOMAIN
        value: "sggs.ac.in"
      - key: CONTACT_EMAIL_EESA
        value: "eesa@sggs.ac.in"
      - key: CONTACT_EMAIL_HOD
        value: "head.ee@sggs.ac.in"
    disk:
      name: eesa-uploads
      mountPath: /var/www/html/uploads
      sizeGB: 1
